name: Main
on:
  pull_request:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: macos-13
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # This action checks-out your repository under $GITHUB_WORKSPACE , so your workflow can access it
      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_14.3.1.app
      - name: Check Xcode Version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild build-for-testing CODE_SIGNING_ALLOWED=NO -scheme "POC-GithubActions" -destination "platform=iOS Simulator,name=iPhone 14"
      - name: Test
        run: xcodebuild test-without-building -scheme "POC-GitbuhActions" -destination "platform=iOS Simulator,name=iPhone 14"
        



        
